### ISSUE TITLE
South migration fails with bitfield

### ISSUE THREAD

**Issue by bdejong** [disqus/django-bitfield#21]
I switched one of my positive integer fields to a bitfield, and migration gave me:

```
Running migrations for activation:
 - Migrating forwards to 0014_auto__chg_field_productrelease_binary_subtype.
 > activation:0014_auto__chg_field_productrelease_binary_subtype
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Python27\lib\site-packages\django\core\management\__init__.py", line 443, in execute_from_command_line
    utility.execute()
  File "C:\Python27\lib\site-packages\django\core\management\__init__.py", line 382, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Python27\lib\site-packages\django\core\management\base.py", line 196, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "C:\Python27\lib\site-packages\django\core\management\base.py", line 232, in execute
    output = self.handle(*args, **options)
  File "C:\Python27\lib\site-packages\south\management\commands\migrate.py", line 108, in handle
    ignore_ghosts = ignore_ghosts,
  File "C:\Python27\lib\site-packages\south\migration\__init__.py", line 213, in migrate_app
    success = migrator.migrate_many(target, workplan, database)
  File "C:\Python27\lib\site-packages\south\migration\migrators.py", line 235, in migrate_many
    result = migrator.__class__.migrate_many(migrator, target, migrations, database)
  File "C:\Python27\lib\site-packages\south\migration\migrators.py", line 310, in migrate_many
    result = self.migrate(migration, database)
  File "C:\Python27\lib\site-packages\south\migration\migrators.py", line 133, in migrate
    result = self.run(migration)
  File "C:\Python27\lib\site-packages\south\migration\migrators.py", line 99, in run
    south.db.db.current_orm = self.orm(migration)
  File "C:\Python27\lib\site-packages\south\migration\migrators.py", line 260, in orm
    return migration.orm()
  File "C:\Python27\lib\site-packages\south\utils\__init__.py", line 62, in method
    value = function(self)
  File "C:\Python27\lib\site-packages\south\migration\base.py", line 431, in orm
    return FakeORM(self.migration_class(), self.app_label())
  File "C:\Python27\lib\site-packages\south\orm.py", line 45, in FakeORM
    _orm_cache[args] = _FakeORM(*args)
  File "C:\Python27\lib\site-packages\south\orm.py", line 124, in __init__
    self.models[name] = self.make_model(app_label, model_name, data)
  File "C:\Python27\lib\site-packages\south\orm.py", line 317, in make_model
    field = self.eval_in_context(code, app, extra_imports)
  File "C:\Python27\lib\site-packages\south\orm.py", line 235, in eval_in_context
    return eval(code, globals(), fake_locals)
  File "<string>", line 1
    SouthFieldClass(default=, max_length=64, db_index=True)
                            ^
SyntaxError: invalid syntax
```

**Comment by iamahuman** [comment]
Django < 1.8 support is dropped, so perhaps this should be closed?

**Comment by timabbott** [comment]
Yeah, that seems right to me; South is long dead.  Thanks for the report @bdejong!
