### ISSUE TITLE
Import error with Apache/mod_wsgi

### ISSUE THREAD

**Issue by LukeSkyw** [disqus/django-bitfield#56]
Hi,
I have installed bitfield in my virtualenv using pip (like I do for all the package). The bitfield module is properly installed in the site-package folder. In my dev environement, I can import bitfield without any trouble. When I do the same on my prod server it fails with an ImportError.
The bitfield package is here and properly installed.
I use mod_wsgi with apache and python 2.7.3 on my server. In django.wsgi I reconfigure my python path to point to my virtualenv (and this has been working for two years and I am using many packages)
When I launch the django shell (./manage.py shell) I can import bitfield no problem:
> \>\>\> from bitfield import BitField # this work ok.

But when I try to load a page, it will fail with:

> Traceback (most recent call last):
>   File "/home/jedi/sites/django-1.6.2-env/lib/python2.7/site-packages/django/core/handlers/base.py", line 90, in get_response
>     response = middleware_method(request)
>   File "/home/jedi/sites/django-1.6.2-env/lib/python2.7/site-packages/lockdown/middleware.py", line 96, in process_request
>     form = form_class(data=form_data, **self.form_kwargs)
>   File "/home/jedi/sites/django-1.6.2-env/lib/python2.7/site-packages/lockdown/forms.py", line 38, in __init__
>     super(LockdownForm, self).__init__(*args, **kwargs)
>   File "/home/jedi/sites/django-1.6.2-env/lib/python2.7/site-packages/django/forms/forms.py", line 90, in __init__
>     self.label_suffix = label_suffix if label_suffix is not None else _(':')
>   File "/home/jedi/sites/django-1.6.2-env/lib/python2.7/site-packages/django/utils/translation/__init__.py", line 76, in ugettext
>     return _trans.ugettext(message)
>   File "/home/jedi/sites/django-1.6.2-env/lib/python2.7/site-packages/django/utils/translation/trans_real.py", line 281, in ugettext
>     return do_translate(message, 'ugettext')
>   File "/home/jedi/sites/django-1.6.2-env/lib/python2.7/site-packages/django/utils/translation/trans_real.py", line 263, in do_translate
>     _default = translation(settings.LANGUAGE_CODE)
>   File "/home/jedi/sites/django-1.6.2-env/lib/python2.7/site-packages/django/utils/translation/trans_real.py", line 177, in translation
>     default_translation = _fetch(settings.LANGUAGE_CODE)
>   File "/home/jedi/sites/django-1.6.2-env/lib/python2.7/site-packages/django/utils/translation/trans_real.py", line 159, in _fetch
>     app = import_module(appname)
>   File "/home/jedi/sites/django-1.6.2-env/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
>     __import__(name)
> [... application related stuff anonymized ...]
>     from bitfield import BitField
> ImportError: No module named bitfield

Also tried 
> from bitfield.models import BitField

But no luck.
Plus, from the command line, this works ok:
> python /path/to/my/website/django.wsgi

Note that I can import many other modules with no problem whatsoever... What is specific about django-bitfield??
Again the path is properly set in the .wsgi loader as many other package are being used by the site (including django !).

Any help is appreciated...
Thanks.

**Comment by LukeSkyw** [comment]
Ok, the issue is due to some weird right issues on the package files. It is related to my system, not django-bitfield.
