### ISSUE TITLE
BitFieldCheckboxSelectMultiple breaks Django Admin Add if the BitField has a default value

### ISSUE THREAD

**Issue by OOPMan** [disqus/django-bitfield#60]
I discovered this the hard way. It seems that if you get a default value for a BitField and then attempt to use the BitFieldCheckboxSelectMultiple widget in the Add view for the model the Django Forms code breaks because it attempts to iterate through the numeric BitField value as if it were a list.

I have forked the code and will be submitting a PR shortly.

For now, enjoy this traceback:

```
ERROR: Internal Server Error: /admin/recomed/practitioner/add/ 
Traceback (most recent call last):
  File "/home/adamj/Development/Tools/Python/VirtualEnv/x86_64/recomed-pypy-2.5.0-kubuntu/site-packages/django/core/handlers/base.py", line 140, in get_response
    response = response.render()
  File "/home/adamj/Development/Tools/Python/VirtualEnv/x86_64/recomed-pypy-2.5.0-kubuntu/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/home/adamj/Development/Tools/Python/VirtualEnv/x86_64/recomed-pypy-2.5.0-kubuntu/site-packages/django/template/response.py", line 82, in rendered_content
    content = template.render(context)
  File "/home/adamj/Development/Tools/Python/VirtualEnv/x86_64/recomed-pypy-2.5.0-kubuntu/site-packages/django/template/base.py", line 140, in render
    return self._render(context)
  File "/home/adamj/Development/Tools/Python/VirtualEnv/x86_64/recomed-pypy-2.5.0-kubuntu/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/home/adamj/Development/Tools/Python/VirtualEnv/x86_64/recomed-pypy-2.5.0-kubuntu/site-packages/django/template/base.py", line 830, in render
    bit = self.render_node(node, context)
  File "/home/adamj/Development/Tools/Python/VirtualEnv/x86_64/recomed-pypy-2.5.0-kubuntu/site-packages/django/template/base.py", line 844, in render_node
    return node.render(context)
  File "/home/adamj/Development/Tools/Python/VirtualEnv/x86_64/recomed-pypy-2.5.0-kubuntu/site-packages/django/template/loader_tags.py", line 124, in render
    return compiled_parent._render(context)
  File "/home/adamj/Development/Tools/Python/VirtualEnv/x86_64/recomed-pypy-2.5.0-kubuntu/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/home/adamj/Development/Tools/Python/VirtualEnv/x86_64/recomed-pypy-2.5.0-kubuntu/site-packages/django/template/base.py", line 830, in render
    bit = self.render_node(node, context)
  File "/home/adamj/Development/Tools/Python/VirtualEnv/x86_64/recomed-pypy-2.5.0-kubuntu/site-packages/django/template/base.py", line 844, in render_node
    return node.render(context)
  File "/home/adamj/Development/Tools/Python/VirtualEnv/x86_64/recomed-pypy-2.5.0-kubuntu/site-packages/django/template/loader_tags.py", line 124, in render
    return compiled_parent._render(context)
  File "/home/adamj/Development/Tools/Python/VirtualEnv/x86_64/recomed-pypy-2.5.0-kubuntu/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/home/adamj/Development/Tools/Python/VirtualEnv/x86_64/recomed-pypy-2.5.0-kubuntu/site-packages/django/template/base.py", line 830, in render
    bit = self.render_node(node, context)
  File "/home/adamj/Development/Tools/Python/VirtualEnv/x86_64/recomed-pypy-2.5.0-kubuntu/site-packages/django/template/base.py", line 844, in render_node
    return node.render(context)
  File "/home/adamj/Development/Tools/Python/VirtualEnv/x86_64/recomed-pypy-2.5.0-kubuntu/site-packages/django/template/loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "/home/adamj/Development/Tools/Python/VirtualEnv/x86_64/recomed-pypy-2.5.0-kubuntu/site-packages/django/template/base.py", line 830, in render
    bit = self.render_node(node, context)
  File "/home/adamj/Development/Tools/Python/VirtualEnv/x86_64/recomed-pypy-2.5.0-kubuntu/site-packages/django/template/base.py", line 844, in render_node
    return node.render(context)
  File "/home/adamj/Development/Tools/Python/VirtualEnv/x86_64/recomed-pypy-2.5.0-kubuntu/site-packages/django/template/loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "/home/adamj/Development/Tools/Python/VirtualEnv/x86_64/recomed-pypy-2.5.0-kubuntu/site-packages/django/template/base.py", line 830, in render
    bit = self.render_node(node, context)
  File "/home/adamj/Development/Tools/Python/VirtualEnv/x86_64/recomed-pypy-2.5.0-kubuntu/site-packages/django/template/base.py", line 844, in render_node
    return node.render(context)
  File "/home/adamj/Development/Tools/Python/VirtualEnv/x86_64/recomed-pypy-2.5.0-kubuntu/site-packages/django/template/defaulttags.py", line 196, in render
    nodelist.append(node.render(context))
  File "/home/adamj/Development/Tools/Python/VirtualEnv/x86_64/recomed-pypy-2.5.0-kubuntu/site-packages/django/template/loader_tags.py", line 156, in render
    return self.render_template(self.template, context)
  File "/home/adamj/Development/Tools/Python/VirtualEnv/x86_64/recomed-pypy-2.5.0-kubuntu/site-packages/django/template/loader_tags.py", line 138, in render_template
    output = template.render(context)
  File "/home/adamj/Development/Tools/Python/VirtualEnv/x86_64/recomed-pypy-2.5.0-kubuntu/site-packages/django/template/base.py", line 140, in render
    return self._render(context)
  File "/home/adamj/Development/Tools/Python/VirtualEnv/x86_64/recomed-pypy-2.5.0-kubuntu/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/home/adamj/Development/Tools/Python/VirtualEnv/x86_64/recomed-pypy-2.5.0-kubuntu/site-packages/django/template/base.py", line 830, in render
    bit = self.render_node(node, context)
  File "/home/adamj/Development/Tools/Python/VirtualEnv/x86_64/recomed-pypy-2.5.0-kubuntu/site-packages/django/template/base.py", line 844, in render_node
    return node.render(context)
  File "/home/adamj/Development/Tools/Python/VirtualEnv/x86_64/recomed-pypy-2.5.0-kubuntu/site-packages/django/template/defaulttags.py", line 196, in render
    nodelist.append(node.render(context))
  File "/home/adamj/Development/Tools/Python/VirtualEnv/x86_64/recomed-pypy-2.5.0-kubuntu/site-packages/django/template/defaulttags.py", line 196, in render
    nodelist.append(node.render(context))
  File "/home/adamj/Development/Tools/Python/VirtualEnv/x86_64/recomed-pypy-2.5.0-kubuntu/site-packages/django/template/defaulttags.py", line 285, in render
    return nodelist.render(context)
  File "/home/adamj/Development/Tools/Python/VirtualEnv/x86_64/recomed-pypy-2.5.0-kubuntu/site-packages/django/template/base.py", line 830, in render
    bit = self.render_node(node, context)
  File "/home/adamj/Development/Tools/Python/VirtualEnv/x86_64/recomed-pypy-2.5.0-kubuntu/site-packages/django/template/base.py", line 844, in render_node
    return node.render(context)
  File "/home/adamj/Development/Tools/Python/VirtualEnv/x86_64/recomed-pypy-2.5.0-kubuntu/site-packages/django/template/defaulttags.py", line 285, in render
    return nodelist.render(context)
  File "/home/adamj/Development/Tools/Python/VirtualEnv/x86_64/recomed-pypy-2.5.0-kubuntu/site-packages/django/template/base.py", line 830, in render
    bit = self.render_node(node, context)
  File "/home/adamj/Development/Tools/Python/VirtualEnv/x86_64/recomed-pypy-2.5.0-kubuntu/site-packages/django/template/base.py", line 844, in render_node
    return node.render(context)
  File "/home/adamj/Development/Tools/Python/VirtualEnv/x86_64/recomed-pypy-2.5.0-kubuntu/site-packages/django/template/base.py", line 887, in render
    return _render_value_in_context(output, context)
  File "/home/adamj/Development/Tools/Python/VirtualEnv/x86_64/recomed-pypy-2.5.0-kubuntu/site-packages/django/template/base.py", line 865, in _render_value_in_context
    value = force_text(value)
  File "/home/adamj/Development/Tools/Python/VirtualEnv/x86_64/recomed-pypy-2.5.0-kubuntu/site-packages/django/utils/encoding.py", line 99, in force_text
    s = s.__unicode__()
  File "/home/adamj/Development/Tools/Python/VirtualEnv/x86_64/recomed-pypy-2.5.0-kubuntu/site-packages/django/forms/forms.py", line 411, in __str__
    return self.as_widget()
  File "/home/adamj/Development/Tools/Python/VirtualEnv/x86_64/recomed-pypy-2.5.0-kubuntu/site-packages/django/forms/forms.py", line 458, in as_widget
    return widget.render(name, self.value(), attrs=attrs)
  File "/home/adamj/Development/Tools/Python/VirtualEnv/x86_64/recomed-pypy-2.5.0-kubuntu/site-packages/bitfield/forms.py", line 15, in render
    name, value, attrs=attrs, choices=enumerate(choices))
  File "/home/adamj/Development/Tools/Python/VirtualEnv/x86_64/recomed-pypy-2.5.0-kubuntu/site-packages/django/forms/widgets.py", line 761, in render
    str_values = set([force_text(v) for v in value])
TypeError: 'int' object is not iterable
```

The issue is that the code in BitFieldCheckboxSelectMultiple.render only checks if value is an instance of BitHandler and does not handle the scenario in which it is an integer.

For some context, my record is defined as so:

```
reason_for_visit_usage_options = (
    ('use_own', 'Use Custom Reasons for Visits'),
    ('use_profession', 'Use Profession-specific Reasons For Visits'),
    ('use_generic', 'Use Generic Reasons for Visits')
)

default_reason_for_visit_usage = (
    reason_for_visit_usage_options[0][0],
    reason_for_visit_usage_options[1][0],
    reason_for_visit_usage_options[2][0],
)

class Practitioner(models.Model):
    reason_for_visit_usage = BitField(flags=reason_for_visit_usage_options, default=default_reason_for_visit_usage, null=False, blank=False)
```

**Comment by OOPMan** [comment]
Hmmmmm, I see this is fixed in the the master, nvm.
