### ISSUE TITLE
'SQLEvaluator' object is not iterable when using admin filter on Django 1.7

### ISSUE THREAD

**Issue by ALenfant** [disqus/django-bitfield#61]
I'm having a problem using the admin page filter on Django 1.7, which I didn't have before the commit ff2e97f2b7ebdf58a0b2554821ffee9c8f6c8c16.

When I filter using one of the available flags (URL being `http://127.0.0.1:8000/admin/my_app/mymodel/?flags=32`, I have the following error:

```
Internal Server Error: /admin/my_app/mymodel/
Traceback (most recent call last):
  File "/home/alenfant/project/venv/lib/python3.4/site-packages/django/core/paginator.py", line 72, in _get_count
    self._count = self.object_list.count()
  File "/home/alenfant/project/venv/lib/python3.4/site-packages/django/db/models/query.py", line 338, in count
    return self.query.get_count(using=self.db)
  File "/home/alenfant/project/venv/lib/python3.4/site-packages/django/db/models/sql/query.py", line 436, in get_count
    number = obj.get_aggregation(using=using)[None]
  File "/home/alenfant/project/venv/lib/python3.4/site-packages/django/contrib/gis/db/models/sql/query.py", line 76, in get_aggregation
    return super(GeoQuery, self).get_aggregation(using, force_subq)
  File "/home/alenfant/project/venv/lib/python3.4/site-packages/django/db/models/sql/query.py", line 402, in get_aggregation
    result = query.get_compiler(using).execute_sql(SINGLE)
  File "/home/alenfant/project/venv/lib/python3.4/site-packages/django/db/models/sql/compiler.py", line 775, in execute_sql
    sql, params = self.as_sql()
  File "/home/alenfant/project/venv/lib/python3.4/site-packages/django/db/models/sql/compiler.py", line 109, in as_sql
    where, w_params = self.compile(self.query.where)
  File "/home/alenfant/project/venv/lib/python3.4/site-packages/django/db/models/sql/compiler.py", line 80, in compile
    return node.as_sql(self, self.connection)
  File "/home/alenfant/project/venv/lib/python3.4/site-packages/django/db/models/sql/where.py", line 106, in as_sql
    sql, params = qn.compile(child)
  File "/home/alenfant/project/venv/lib/python3.4/site-packages/django/db/models/sql/compiler.py", line 80, in compile
    return node.as_sql(self, self.connection)
  File "/home/alenfant/project/venv/lib/python3.4/site-packages/django/db/models/lookups.py", line 149, in as_sql
    lhs_sql, params = self.process_lhs(qn, connection)
  File "/home/alenfant/project/venv/src/django-bitfield/bitfield/query.py", line 33, in process_lhs
    params.extend(self.get_db_prep_lookup(self.rhs, connection)[1])
TypeError: 'SQLEvaluator' object is not iterable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/alenfant/project/venv/lib/python3.4/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/alenfant/project/venv/lib/python3.4/site-packages/django/contrib/admin/options.py", line 583, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/home/alenfant/project/venv/lib/python3.4/site-packages/django/utils/decorators.py", line 105, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/alenfant/project/venv/lib/python3.4/site-packages/django/views/decorators/cache.py", line 52, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/alenfant/project/venv/lib/python3.4/site-packages/django/contrib/admin/sites.py", line 206, in inner
    return view(request, *args, **kwargs)
  File "/home/alenfant/project/venv/lib/python3.4/site-packages/django/utils/decorators.py", line 29, in _wrapper
    return bound_func(*args, **kwargs)
  File "/home/alenfant/project/venv/lib/python3.4/site-packages/django/utils/decorators.py", line 105, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/alenfant/project/venv/lib/python3.4/site-packages/django/utils/decorators.py", line 25, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/home/alenfant/project/venv/lib/python3.4/site-packages/django/contrib/admin/options.py", line 1485, in changelist_view
    self.list_max_show_all, self.list_editable, self)
  File "/home/alenfant/project/venv/lib/python3.4/site-packages/django/contrib/admin/views/main.py", line 110, in __init__
    self.get_results(request)
  File "/home/alenfant/project/venv/lib/python3.4/site-packages/django/contrib/admin/views/main.py", line 219, in get_results
    result_count = paginator.count
  File "/home/alenfant/project/venv/lib/python3.4/site-packages/django/core/paginator.py", line 77, in _get_count
    self._count = len(self.object_list)
  File "/home/alenfant/project/venv/lib/python3.4/site-packages/django/db/models/query.py", line 122, in __len__
    self._fetch_all()
  File "/home/alenfant/project/venv/lib/python3.4/site-packages/django/db/models/query.py", line 966, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/home/alenfant/project/venv/lib/python3.4/site-packages/django/db/models/query.py", line 265, in iterator
    for row in compiler.results_iter():
  File "/home/alenfant/project/venv/lib/python3.4/site-packages/django/db/models/sql/compiler.py", line 700, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/home/alenfant/project/venv/lib/python3.4/site-packages/django/db/models/sql/compiler.py", line 775, in execute_sql
    sql, params = self.as_sql()
  File "/home/alenfant/project/venv/lib/python3.4/site-packages/django/db/models/sql/compiler.py", line 109, in as_sql
    where, w_params = self.compile(self.query.where)
  File "/home/alenfant/project/venv/lib/python3.4/site-packages/django/db/models/sql/compiler.py", line 80, in compile
    return node.as_sql(self, self.connection)
  File "/home/alenfant/project/venv/lib/python3.4/site-packages/django/db/models/sql/where.py", line 106, in as_sql
    sql, params = qn.compile(child)
  File "/home/alenfant/project/venv/lib/python3.4/site-packages/django/db/models/sql/compiler.py", line 80, in compile
    return node.as_sql(self, self.connection)
  File "/home/alenfant/project/venv/lib/python3.4/site-packages/django/db/models/lookups.py", line 149, in as_sql
    lhs_sql, params = self.process_lhs(qn, connection)
  File "/home/alenfant/project/venv/src/django-bitfield/bitfield/query.py", line 33, in process_lhs
    params.extend(self.get_db_prep_lookup(self.rhs, connection)[1])
TypeError: 'SQLEvaluator' object is not iterable
```

**Comment by moumoutte** [comment]
It seems to appear in search mode. Using  with django-filters and DRF, we get the same results.

**Comment by X-Treem** [comment]
Today I've got exactly the same. Crash happens when queryset tries to evaluate ```bitor(F(p), v))```.
The same crash happens in console, when I type something like ```Model.objects.filter(F('flags').bitand('2'))```

**Comment by brechin** [comment]
This seems to address the issue (since this repo appears to be maybe-no-longer-maintained):

```py
class BitFieldListFilterFixed(BitFieldListFilter):
    def queryset(self, request, queryset):
        filter_params = dict((p, v) for p, v in iteritems(self.used_parameters))
        try:
            return queryset.filter(**filter_params)
        except ValidationError as e:
            raise IncorrectLookupParameters(e)
```
